dist: xenial

language: node_js

node_js:
- lts/*

cache:
  directories:
  - "$HOME/.npm"

git:
  depth: 3

before_install:

before_script:
- chmod 600 ./deploy_key
- echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- ssh-add ./deploy_key

script:
- npm run build

after_script:
- bash scripts/deploy.sh
