dist: xenial

language: node_js

node_js:
- lts/*

cache:
  directories:
  - "$HOME/.npm"

git:
  depth: 3

before_install:
- openssl aes-256-cbc -K $encrypted_ac07c5c7b1b7_key -iv $encrypted_ac07c5c7b1b7_iv -in deploy_key.enc -out ./deploy_key -d

before_script:
- chmod 600 ./deploy_key
- echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- ssh-add ./deploy_key

script:
- yarn build

after_script:
- bash scripts/deploy.sh
